### ISSUE TITLE
Add dropdown for thread selection

### ISSUE THREAD

**Issue by uber-mahyar2** [jlfwong/speedscope#167]
Instead of having to go through each thread with left and right buttons, it would be nice to be able to skip to a specific thread with a drop down menu.   Also you could put thread span count and start time in the drop down, so we can more easily differentiate between different threads.

I would put the dropdown where the thread name is.

**Comment by jlfwong** [comment]
Yeah, this makes sense to me! This is a non-trivial bit of work since I don't have any other dropdowns in speedscope right now, so I'd have to design that first before actually doing this. (I'm generally not interested in integrating a third party UI library into speedscope, so I'd be building this from scratch).

Like a few other issues, I'll put this under the donation clause to prioritize working on this:

---

I’ll commit to implementing this feature myself if a total of $200 of donations is made to any combination of these specific charities:

- [American Civil Liberties Union](https://www.aclu.org/)
- [/dev/color](https://www.devcolor.org/welcome): /dev/color is a non-profit organization whose mission is to empower Black software engineers to help one another grow into industry leaders.
- [Girls Who Code](https://girlswhocode.com/about-us/): Girls Who Code was founded with a single mission: to close the gender gap in technology

If you’d like to contribute to that total, please post a screenshot of your donation receipt in this thread*.

Independent of that, I would accept a PR to implement this, regardless of donation amounts.

*: I'm planning on trying this policy on a number of issues. Donations will apply to the total of exactly one issue, so please don't post the same receipt in multiple issue threads.

**Comment by retronym** [comment]
It would also be useful to have an option on the left-heavy and sandwich views to aggregate the profiles from all threads.

**Comment by espes** [comment]
<img width="552" alt="Screen Shot 2020-05-02 at 10 10 17 pm" src="https://user-images.githubusercontent.com/426116/80892415-c16dd980-8cc1-11ea-96c1-cfec7dd835a5.png">

**Comment by jlfwong** [comment]
@espes Thank you!! 🎉 

I'll try to get started on this later today for accountability and to get input. I'm not going to commit to a specific delivery time for this, but I'll do my best to make some amount of progress on this each week.

**Comment by jlfwong** [comment]
Small progress working on some mockups for this. If people in this thread could share their use cases for why the current thread switcher is annoying, that would help to guide my work here. I'm sure it is annoying for any situation where you have more than two threads. The example data I'm using comes from a real chrome://tracing run which has > 100 threads, so I figure it should be a decent heavy load use case.

GIF: (click to see full res)
![2020-05-04 23 13 05](https://user-images.githubusercontent.com/150329/81039086-e8144780-8e5c-11ea-8484-9706ce12ea72.gif)

Interactive Figma Prototype:
https://www.figma.com/proto/WxI0iCOfbfv9l3el6jfBy7/Speedscope-UI-Explorations?node-id=5%3A16&scaling=scale-down

As I said, I'll be making slow progress on this over the next few weeks. In the meantime, if you have feedback on how the UI for this should work, I'm open to it!

Some specific questions:
- Would this UI be useful with only the dropdown and no filtering, or do you think the filtering is crucial for this to be useful?
- If there's a dropdown, are the left & right arrows still useful, or should they be removed entirely?

**Comment by jlfwong** [comment]
@espes @uber-mahyar2 In #282 I have an initial implementation of this up and running. If you could take a look at that, I'd love to have any feedback before landing this.

**Comment by jlfwong** [comment]
@espes @uber-mahyar2 This is now landed and published as speedscope 1.6.0 on npm, and live on https://speedscope.app.

Thanks again for the donation @espes!
