### ISSUE TITLE
chrome profile: reported time isn't the same as dev tools

### ISSUE THREAD

**Issue by vmarchaud** [jlfwong/speedscope#176]
I was working on support an older format of cpu profile when i noticed some difference between the values reported by speedscope and by devtools : 

![image](https://user-images.githubusercontent.com/2820968/46615803-70aff200-cb19-11e8-8cb8-cc729da78c06.png)

Both are ordered by self time but we see a lot of difference in the list. Also we don't report the idle time in speedscope, i believe we should ?

I'm willing to put some time to inspect it, just opening an issue to keep you up to date ;)

**Comment by jlfwong** [comment]
It's possible this is a bug in the import, or a bug elsewhere in speedscope, though it isn't a specific goal to have this information map 1: w/ what devtools reports.

A specific example of something speedscope does that will result in a misalignment is to consider certain function calls to be part of whatever the previous stack was. As an example, the file format places `(garbage collector)` as a top-level frame in the profiler, but speedscope places it on top of whatever stack immediately precedes it. We do a similar thing for the opaque `(program)` calls.

See e.g. #85.

I don't confidently know offhand what would be causing this misalignment though, so it may be worth investigating and understanding it. It's possible however, that we'll discover it's an intentional different interpretation of the data.

**Comment by vmarchaud** [comment]
Well the main problem for me is that if the devtools show it in this specific way, i believe its meant to be understand like this.
However we can see considerable difference between devtools and speedscope (for exemple the `idiff` total time, i will for sure inspect what's going on to be able to explain it

**Comment by vmarchaud** [comment]
For merging some frames, i need some digging to better understand how its working. But if the thread is blocked when the GC is running, i believe speedscope should show it as a top level frame, and same for the `(program)` (which is [apparently ](https://stackoverflow.com/questions/3847954/what-is-program-in-chrome-debugger-s-profiler)v8 itself)
