### ISSUE TITLE
Failed to load format TypeError: Cannot read property 'reduce' of undefined

### ISSUE THREAD

**Issue by lara** [jlfwong/speedscope#200]
Following the documentation on [importing from stackprof](https://github.com/jlfwong/speedscope/wiki/Importing-from-stackprof-(ruby)), I get this `TypeError` in the JS console as I attempt to import the generated JSON file. 

Is this a bug or am I missing something?

**Comment by jlfwong** [comment]
Hi @lara!

I haven't seen that problem before. Can you either provide a sample profile that's hitting this issue or a script I can run to generate one?

If I run the exact script there in which nothing is being profiled, I do indeed hit the error you're describing, so that's for sure a bug.

Running the following script which was used to generate the test file in speedscope's own test suite, I don't hit this issue:

```
# foo.rb
require 'json'
require 'stackprof'

def a
  for i in 0..100 do
    b
    c
  end
end

def b
  for i in 0..10
    d
  end
end

def c
  for i in 0..10
    d
  end
end

def d
  prod = 1
  for i in 1..1000
    prod *= i
  end
  prod
end

profile = StackProf.run(mode: :wall, raw: true) do
  a
end

puts JSON.generate(profile)
```

```
ruby foo.rb > foo.json
```

This might just be a bug with importing empty profiles from stackprof, but if you have a non-empty profile that runs into this, that would be helpful information!

**Comment by lara** [comment]
It's definitely not an empty profile. In fact, it's pretty loaded. I'll try to reproduce with something simpler that runs into the same issue and update you with that.

**Comment by jlfwong** [comment]
@lara I suspect the issue is not the size of the profile, but it's hard to know without a specific repro case. If you have even large repro cases that you can share, then I can dig into it. speedscope in general can handle extremely large profiles, and was designed and optimized with that in mind.

It's suspicious to me that the issue you're running into has the same error message as empty profiles, so maybe it's the same root cause regardless. If you aren't able to share the profile, then I can try to fix the empty case, and see if that also resolves your issue.

Thanks for keeping me posted! Let me know if you uncover more details!

**Comment by lara** [comment]
Oh the case is absolutely not that the profile is empty, I can tell you that with 100% confidence. But I will keep you posted on any details I may run into.

Thank you for your promptness.

**Comment by jlfwong** [comment]
@lara Yeah, sorry, I didn't mean to suggest that your profile was empty. I was suggesting that whatever is causing the crash that I can reproduce with an empty profile might also be causing the crash with your profiles.

**Comment by jlfwong** [comment]
Hi @lara 

From looking at the crashing case for empty profiles, it's because the `raw_timestamp_deltas` field is entirely missing from the JSON output. The empty profile looks like this:

```
{"version":1.2,"mode":"wall","interval":1000,"samples":0,"gc_samples":0,"missed_samples":0,"frames":{}}
```

Is it possible that you're missing the `raw: true` argument to `StackProf.run`? speedscope relies upon the `raw_timestamp_deltas` field being present in the JSON output.

**Comment by jaimerson** [comment]
I had this same issue and solved it by updating `stackprof`. `raw_timestamp_deltas` was only introduced in `0.2.11` and I was using `0.2.9`.

**Comment by lara** [comment]
Hi @jlfwong 

Sorry for the misunderstanding. I didn't have a lot of time to look into this and had to resort to using a not-the-best-UI flamegraph, but after @jaimerson's comment, I decided to give it another shot.

The profile I had before and after has a single difference, which is the `raw_timestamp_deltas` field. After the version change, my profile did have the field which successfully uploaded and displayed the flamegraph. 

So maybe you can update https://github.com/jlfwong/speedscope/wiki/Importing-from-stackprof-(ruby) to mention the version requirement.

**Comment by jlfwong** [comment]
@lara Thanks for getting back to me! I updated the wiki page to include the version requirement. I'll leave this issue open since speedscope shouldn't be crashing, but I'm glad it seems to be working for newer versions of `stackprof`!
