### ISSUE TITLE
`Uncaught SyntaxError: Unexpected token {` in Self-contained  version 

### ISSUE THREAD

**Issue by sillyousu** [jlfwong/speedscope#214]
`Uncaught SyntaxError: Unexpected token {`  in `speedscope.tsx`

**Comment by sillyousu** [comment]
I had a wrong zip file.

**Comment by jlfwong** [comment]
@sillyousu Glad you figured out the issue! What zip file were you downloaded that led to this? Which zip file ended up working for you?

**Comment by sillyousu** [comment]
I downloaded the source code zip file from release page.
I should download the one named `speedscope-1.5.0.zip`.

**Comment by jlfwong** [comment]
Gotcha! Out of curiosity @sillyousu, why did you opt for using the zip file rather than using https://www.speedscope.app/? I made the standalone zip files because it was easy and it's a helpful method for making it easy to integrate into other projects, but I wasn't sure anyone would use it themselves. I'm glad to know it did end up being useful!
