### ISSUE TITLE
Support importing ETW profiles

### ISSUE THREAD

**Issue by jrmuizel** [jlfwong/speedscope#217]
It would be great if speedscope could support importing profiles from ETW/xperf on Windows

**Comment by jlfwong** [comment]
Hi @jrmuizel 

Do you know if there's documentation about the contents of the file format? If so, could you link to it please?

Thanks!

**Comment by jrmuizel** [comment]
It looks like the format is not documented. For now it's probably better to just support the output from https://github.com/Microsoft/ETW2JSON

**Comment by jlfwong** [comment]
Are there any other tools that import this format yet? If you could provide example profiles w/ expected output for visualization, that would help.

I'll caveat this by saying that I don't use ETW profiles for anything I do day-to-day, so I would likely only implement this in response to a donation to a specific charity. See e.g. https://github.com/jlfwong/speedscope/issues/60#issuecomment-419660710 for how go profiler import was motivated.

I won't commit to doing this if donations are met yet, however, because I don't understand enough about the contents of the import to understand the scope of what would be needed to import this, or have any concept of how hard it would be. If you could help me understand what you're hoping to get out of this, then I can consider opening this up to the donation-motivated policy.

**Comment by adamsitnik** [comment]
Some time ago I have implemented a `SpeedScopeExporter ` for ETW. It's now available in TraceEvent library and also in PerfView GUI. Please see https://github.com/Microsoft/perfview/pull/842 for more details

**Comment by jlfwong** [comment]
@adamsitnik Woah, cool!

If you'd like, I'm happy to update documentation and the wiki to reflect instructions on how to import from ETW if you can provide instructions for how to do that.

Here's an example wiki page explaining how to import from a different source from a GUI: https://github.com/jlfwong/speedscope/wiki/Importing-from-Instruments.app, and here's a different from for explaining how to import from a terminal program: https://github.com/jlfwong/speedscope/wiki/Importing-from-rbspy-(ruby).

@jrmuizel Does it sound like that meets your needs?

**Comment by jrmuizel** [comment]
I'll try it out when I get the chance. Thanks.

**Comment by jlfwong** [comment]
Since it sounds like the primary use case of this is probably address by perfview, I'm going to close this.
