### ISSUE TITLE
Minimap isn't visible initially

### ISSUE THREAD

**Issue by pdsharma0** [jlfwong/speedscope#218]
Right after loading my json file, I am not able to zoom into the minimap as it only shows drag icon. I have to press the down arrow to bringup a small section of greyed-out zoomable zone. It's probably because I have no stacked-frames in my file. Shouldn't a part of it be visible for zoom to always work?

I was under the impression that there's a clear divide between the minimap and frames below based on the help : https://github.com/jlfwong/speedscope#usage

**Comment by jlfwong** [comment]
Hi @pdsharma0!

I'm not quite sure what you're referring to. If you can provide a test file and a screenshot, that would really help me investigate the issue.

**Comment by pdsharma0** [comment]
Hello @jlfwong,

Please take a look at my screenshots. The first one is the view when I load the file, there's no grey zone to zoom into. The second one is after I pressed the down arrow key which brings up the grey zone slightly right above the top row of times. I am only able to zoom in that area. 

![screenshot_1](https://user-images.githubusercontent.com/5360117/55664001-28c60b00-57dc-11e9-92c6-aa6c4344aa19.png)
![screenshot_2](https://user-images.githubusercontent.com/5360117/55664002-28c60b00-57dc-11e9-8e4b-e6191bbe02b2.png)

**Comment by pdsharma0** [comment]
I won't let me paste my JSON file here so how do I send it?

**Comment by jlfwong** [comment]
I think copying and pasting the below will replicate the behavior you're talking about:

```
a 1
b 1
```

The minimap refers to the entire region at the top, not the grey zone. So in the context of your screenshot:

![image](https://user-images.githubusercontent.com/150329/55835714-6cb55a80-5ad1-11e9-97b0-75bbe89b0730.png)

In this situation, calling it a minimap is a little strange since it's bigger than the actual trace. The more common case is that you have a very complex trace, like this:

![image](https://user-images.githubusercontent.com/150329/55835757-85be0b80-5ad1-11e9-97ba-25bb974f864f.png)

You can play around with a more complex trace to get a feeling for how the interactions are supposed to work by loading an example file on speedscope.app by clicking the link on the welcome screen: 

![image](https://user-images.githubusercontent.com/150329/55835887-d170b500-5ad1-11e9-8bc0-d2c7d950980f.png)


I don't think there's any unexpected behavior happening here, but if I've misunderstood, please let me know and I'll re-open the issue!

**Comment by pdsharma0** [comment]
It's alright, my use-case is a bit different than what the speedscope was originally designed for I guess. I am trying to visualize execution of work-packets on GPU interfaces which are really heavy in number of data objects, so always-on zoom-ability is quite desirable in such cases.  It's all good though, as it's open-source and we can fork from the baseline functionality you have and add stuff that we need.
