### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by apnewberry** [jlfwong/speedscope#220]
I'd love to have a dark theme for nighttime use! 😎

**Comment by jlfwong** [comment]
@evanw Sorry it took me so long to respond!

This is really cool! The high-level approach looks right to me, though I think ideally I'd like to specify functional colors by role somewhere and do something like `Color.foregroundText(isDarkMode)` or something along those lines to make it hard to forget to do this when adding new bits of UI in various places, rather than having `isDarkMode` switches everywhere. I've also seen other styling tools pass down a "theme" object via React context to avoid needing to do this at all.

When I have some more time, I'd like to understand how designers manage their color palettes around use case rather than naming the color for theming, since I think that'll apply well in this case too.

**Comment by evanw** [comment]
Makes sense. Sounds like you'd like to take it from here. Is that correct? Let me know if you need anything from me. I'm also happy to help if it's useful.

**Comment by jlfwong** [comment]
Yep! When I have time to look into this and have things in a place I'm happy with, I'll probably send it to you to user test since it sounds like you're maybe one of the heaviest nighttime users 😂

**Comment by jlfwong** [comment]
Okay! This is live on https://www.speedscope.app/ now, and published to npm as speedscope@1.12.0

**Comment by evanw** [comment]
Shoot I didn't catch you. The problem mentioned in https://github.com/jlfwong/speedscope/pull/323#issuecomment-725978352 happens on https://www.speedscope.app/ for me too.

**Comment by jlfwong** [comment]
Welp. Tracking in #327
