### ISSUE TITLE
Failure to load json from custom source.

### ISSUE THREAD

**Issue by ScatteredRay** [jlfwong/speedscope#230]
Attached appears to be a well formed trace as described here: https://github.com/jlfwong/speedscope/wiki/Importing-from-custom-sources
however when loaded, the symbols load correctly, however no sample data appears to load, nor are any errors produced.
[build.speedscope.json.txt](https://github.com/jlfwong/speedscope/files/3592993/build.speedscope.json.txt)

**Comment by jlfwong** [comment]
Hi @ScatteredRay!

Thanks for the report with a clear description & repro! I can repro the behavior you're describing.

From a quick look at the file, while the file is schematically valid, the profile it represents contains only zero-duration events. 

The start of the profile begins like so:

```
{"type":"O","frame":15,"at":11968656},
{"type":"C","frame":15,"at":11968656},
{"type":"O","frame":44,"at":11968968},
{"type":"C","frame":44,"at":11968968}
```

For both of these, the open and close happen at exactly the same time. The kind of profile specified by this file is an "evented" profile, where it's the responsibility of the profiler exporter to specify when a given call stack frame was opened and closed as two distinct events.

Given that, I'm not sure what speedscope should do in this situation, since the profile contains only zero-duration events spaced out in time. So the flamegraph is conceptually a bunch of spaced out zero-width bars.

**Comment by ScatteredRay** [comment]
My mistake! I was having trouble and mucking with the output. I've fixed that issue.

It does however lead to my next issue, which is that my capture is actually of multiple concurrent events, and the O, and C events aren't actually nested. I get that it's not really a 'flame-graph' in that case, but it'd still be super useful to visualize in speedscope.
[build.timeline.json.txt](https://github.com/jlfwong/speedscope/files/3597198/build.timeline.json.txt)

**Comment by jlfwong** [comment]
@ScatteredRay Ah yeah, speedscope fundamentally does not support profiles which represent things other than call-stacks, and I don't have plans to add that in the near future.

If you need support for arbitrary timed event visualization for e.g. waterfall graphs of network requests, for now I'd recommend you output to the chrome tracing format and import into chrome://tracing. See https://docs.google.com/document/d/1CvAClvFfyA5R-PhYUmn5OOQtYMH4h6I0nSsKchNAySU/preview
