### ISSUE TITLE
Add support for loading local profile from URL

### ISSUE THREAD

**Issue by hyee** [jlfwong/speedscope#231]
Speedscope is awesome and I find out that it can be directly opened offline without web server.
This feature is very cool because it eliminates the need on some environment.
One thing I'd preferred is that it can support directly accessing the local profile file in its URL, which 
 is similar to that of `profileURL`,  so that to directly render the profile file without having to browse a file.

I tried `localProfilePath` but it didn't seems to work, for example, `file:///D:/speedscope/index.html?#localProfilePath=d:/speedscope/perf-vertx-stacks-01-collapsed-all.3e0a632c.txt` will raise an error in the console, looks like the target file must be a js file.
Is there anyway to accomplish such purpose? Thanks.

**Comment by jlfwong** [comment]
Hi @hyee!

As far as I know, this is limitation of browsers. For important security reasons, browsers don't allow file loading from arbitrary file paths. Otherwise, it would be possible for websites to steal contents of arbitrary files from your computer.

One way to achieve something close to what you're trying to do would be to run a local server that could serve files off your hard drive, and then request it through a `localhost` URL.
