### ISSUE TITLE
multi-process support for CTF

### ISSUE THREAD

**Issue by milianw** [jlfwong/speedscope#235]
Hey there,

great project! I'd love to use this in stead of chrome://tracing, but some important CTF functionalities are missing. Most notably, it seems like speedscope assumes there's only one thread? That makes the tool unusable for multi-thread/process CTF traces. It would be great if this could be supported.

Here's an example file you could use to check how this looks like in chrome://tracing and then compare it to speedscope:
[trace.json.gz](https://github.com/jlfwong/speedscope/files/3730293/trace.json.gz)

Cheers

**Comment by jlfwong** [comment]
Hi @milianw, I'm glad this project has proved useful to you!

speedscope does support multiple processes -- there are navigation controls to move between processes & threads at the top:

![image](https://user-images.githubusercontent.com/150329/66896713-41448880-efaa-11e9-9fa5-009e5f4ee887.png)

This is definitely not as nice as the display that chrome://tracing offers where you can pan among multiple processes at the same time, but supporting that is a non-trivial change to both the data model & the renderer. I don't have much time to invest into speedscope these days, so this is unlikely to be done by me in the foreseeable future. That issue is tracked as #117, so I'm going to close this one.
