### ISSUE TITLE
Merging of two speedscope.json files

### ISSUE THREAD

**Issue by kunchamlokesh** [jlfwong/speedscope#238]
Hi Team,

I had a requirement where I need to merge multiple speedscope.json files in to single speedscope.json file which is generated by multiple threads using the same code 

Please let me know the possibilities to merge them

**Comment by jlfwong** [comment]
Hi @kunchamlokesh,

You can read about speedscope's file format here: https://github.com/jlfwong/speedscope/wiki/Importing-from-custom-sources#speedscopes-file-format

Since it's a JSON based format, it should be plausible to write some code that ingests two speedscope json files and outputs another one which still conforms to the format.

I'm not aware of any code that does that currently, and I don't think that's the sort of thing that would belong in this repository, so I'm going to close this issue.

Thanks!
