### ISSUE TITLE
Sandwitch Sort by "self". Method displayed twice

### ISSUE THREAD

**Issue by guettli** [jlfwong/speedscope#247]
There is something strange.

The method "test_ids_from_import_done_exist" appears twice:

![image](https://user-images.githubusercontent.com/414336/70148974-82524280-16a7-11ea-9f2a-290c2e62e1a3.png)

And the second:

![image](https://user-images.githubusercontent.com/414336/70149155-d0674600-16a7-11ea-8543-e7d789f93671.png)

Maybe this happens because once it is the lowest line in the stacktrace, and once there are sub-methods below this method.

Data was created by py-spy.

**Comment by jlfwong** [comment]
If you include the profile, I can take a look. This is more likely to be a bug in the py-spy profiler speedscope output than it is to be a bug in speedscope itself

**Comment by benfred** [comment]
I've managed to replicate this, and I've attached the profile output as well as script to generate it below.

I believe the duplicate entries are showing up in the sandwich view because of the line numbers being included in the frames, which aren't shown in the sandwich view but are shown in the time order/ left heavy views.  This causes 1 duplicate entry per line in the sandwich view.
 
A script to generate is

```python
# profile with
# py-spy record -o profile.json -f speedscope --idle --duration 10  -- python ./test.py
import time

def foo():
    time.sleep(0.2)
    time.sleep(0.1)

while True:
    foo()
```

And here is how it looks in the sandwich view, notice that there are two 'foo' entries included there, with the times  roughly corresponding to how long we would expect each sleep line to take:
 
![Screenshot from 2019-12-07 20-22-21](https://user-images.githubusercontent.com/69536/70384160-577a1f80-192f-11ea-8f5a-d0a127ff1bb6.png)

(profile output: [speedscope.json.txt](https://github.com/jlfwong/speedscope/files/3935853/speedscope.json.txt) )

I'm happy to tweak the JSON format from py-spy if I'm doing something wrong here, but it looks to me that the issue is that the speedscope sandwich view isn't showing the line numbers causing a confusing experience.

semi-related issue here: https://github.com/benfred/py-spy/issues/201

**Comment by jlfwong** [comment]
Hi @benfred, thanks for making py-spy!

This is ambiguous, but the line numbers are intended to be line numbers of the function definition, not the line currently active in the stack. In this instance, the line number for `foo` should be the same for samples in which `time.sleep(0.2)` is at the top of the stack and in which `time.sleep(0.1)` is the top of the stack.

When importing from the speedscope file format, only stack frames which have the same frame index (https://github.com/jlfwong/speedscope/blob/bdd9301c59f29c105762b6460d731438c670d705/src/lib/file-format-spec.ts#L84) are aggregated together. This is important to e.g. allow two actually distinct functions with the same name in the same file to be treated separately.

**Comment by benfred** [comment]
Thanks for the response!

I’ve added the ability for py-spy to leave out the line numbers from the speedscope output in the last release (by specifying the -F flag). This should mostly solve this problem @guettli.

I think I understand your point @jlfwong , the line numbers there are meant for disambiguating functions with the same name in the same filename, not for doing line based profiling. I still think that there is a case for including the line numbers in the sandwich view: it would make it consistent with the left heavy / time order views where they are displayed, and without the line numbers there can be entries that look the same (like same function name in same file case).
