### ISSUE TITLE
Onboarding of new team members

### ISSUE THREAD

**Issue by guettli** [jlfwong/speedscope#248]
Looking at the "Insights" tab on github, I see that speedscope is mostly a one-man-show up to now.

How do you want the future to be?

I am a member of some development related facebook groups.

Sometimes the question comes up: What can I do to learn or improve my skills?

Before I redirect young and motivated developers here, I want to talk to you.

Do you see some simple tasks which could get implemented by people who want to learn?

Of course this needs some time and especially patience from you.

What do you think?

**Comment by jlfwong** [comment]
@guettli There are a few tasks labeled "help wanted" that might be reasonable onboarding paths here: https://github.com/jlfwong/speedscope/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22

I don't have a clear plan for how much time I want to invest into code review for others for speedscope. Doing mentorship and code review is something I enjoy a lot in the course of my work, but I have a full-time at Figma doing software engineering where I already spend a lot of time doing that, and am not really interested in spending a lot of time outside of work hours doing that at the moment.

So, while I value and enjoy mentoring junior folks, I don't think speedscope is the right environment to direct them towards to learn. There are many other open source communities with better structures in place to ensure that people joining in get the support they need, so I'd suggest directing them there instead.

I'm open to accepting PRs to speedscope, though I think I'd rather keep it as mostly a "pet project" kind of status where I can change stuff fairly significantly whenever I'd like, rather than trying to accelerate it into a larger community project.

This might change in the future, but I think this is likely going to be my stance for the next year or so.
