### ISSUE TITLE
Feature Request: Importing compressed profiles

### ISSUE THREAD

**Issue by steamp0rt** [jlfwong/speedscope#250]
Some profiles can get pretty big, pretty fast, so it'd be convenient if we could upload compressed profiles and have them be decompressed.

something maybe like this? https://www.npmjs.com/package/zstd-codec

**Comment by jlfwong** [comment]
Hi @steamp0rt!

A few comments on this:
1. If your concern is that compressed files will upload to speedscope faster, then you won't get any benefit from speedscope because no files are uploaded. Instead, speedscope does everything in-browser. So compression will actually make import slower, not faster, since now there's a decompression step that wouldn't otherwise exist.
2. If your profiles just happen to be compressed already, then speedscope will import some formats if they're zlib compressed using [pako](https://www.npmjs.com/package/pako). That's what [MaybeCompressedDataReader](https://github.com/jlfwong/speedscope/blob/bdd9301c59f29c105762b6460d731438c670d705/src/import/utils.ts#L27) does.

Can you explain a bit more about what your use case is here?

**Comment by jlfwong** [comment]
I'm going to close this out for inactivity since I'm not sure what the request is here
