### ISSUE TITLE
Hovering over flamegraph in sandwich view causes label to get cut off

### ISSUE THREAD

**Issue by nightpool** [jlfwong/speedscope#256]
### Actual behavior:

![image](https://user-images.githubusercontent.com/233815/73953571-9cd6b100-48ce-11ea-94bb-46916544b934.png)

### Expected behavior:

![image](https://user-images.githubusercontent.com/233815/73953613-a6f8af80-48ce-11ea-8d3a-3bcddfa5149e.png)

Seems like the issue is caused by some overly-strict `overflow: hidden` styles on the containing blocks. Maybe it would be better to use a [Portal](https://reactjs.org/docs/portals.html) to render the tooltip into a part of the dom that doesn't have `overflow: none` applied? Or remove the overflow: hidden styles

**Comment by nightpool** [comment]
I made a small, hacky userscript to solve the issue on speedscope.app (obviously will break when css gets regenerated) https://gist.githubusercontent.com/nightpool/6a3d5218436295c6fafa991d30409f5a/raw/speedscope_tooltip_fix.user.css

**Comment by jlfwong** [comment]
Oh jeez, good catch. This is definitely a bug.

I'd accept a PR to fix this issue. 

I agree that having it clipped by the container isn't great, but it seems like there's something wrong with the heuristic deciding whether the tip should be to the left or the right of the cursor. I suspect that fixing that will fix the problem in the majority of cases. (e.g. in the screenshot you show, the problem would be resolved if the tooltip was to the right of the cursor instead of left).
