### ISSUE TITLE
Automate dependency updates

### ISSUE THREAD

**Issue by JustinBeckwith** [jlfwong/speedscope#260]
Greetings!  I noticed that a lot of dependencies are out of date, and it's preventing the codebase from building on Node.js 13.x.  One of the things we use to help keep deps up to date is renovate:
https://renovatebot.com/

I like it because it submits PRs for each dependency, making it easier to update one thing at a time.  Might help reduce the maintenance burden!

**Comment by bjorn3** [comment]
Just curious, but what is the difference between renovatebot and the github owned dependabot?

**Comment by JustinBeckwith** [comment]
At a glance, Dependabot looks great!  I only suggested renovate because it's the tool I'm most familiar with.

**Comment by jlfwong** [comment]
Hi!

I don't have really strong feelings here, but I generally like to avoid taking on dependencies until I personally repeatedly face problems I'd like to automate away. The majority of the pain from dependency upgrades isn't finding versions to bump to, it's fixing all the problems that are caused by incompatibilities, so I'm not sure what I get out of this.

The fact that it doesn't build on Node.js 13.x is concerning to me, but can you please file that as a separate issue?
