### ISSUE TITLE
feature: WASD navigation

### ISSUE THREAD

**Issue by paulirish** [jlfwong/speedscope#3]
In the DevTools (and about:tracing) we allow panning Y axis with A/D and zooming Y axis with W/S. I've come to heavily rely on that, so I'd lurve if it was supported here, too.

Greattt work on this app. So nice.

**Comment by jlfwong** [comment]
👋 @paulirish  😄 

a & d should already pan to the left and right, which I believe they do in chrome devtools too.
w & s currently pan up and down in the case of deep stack traces.

I departed from some of the other conventions of devtools intentionally -- namely that scrolling up and down pans rather than zooms, since I always find myself needing to drag around to see what's at the top of the stack in chrome devtools.

There are existing hotkeys for zooming in and out (+ and -), though admittedly those are not available on the left-hand side for QWERTY keyboard layout. Perhaps `q` and `e` would be reasonable choices?

**Comment by jlfwong** [comment]
I'm not planning on adding these hotkeys, so I'm going to close this
