### ISSUE TITLE
profileURL refers to the same host

### ISSUE THREAD

**Issue by amosbird** [jlfwong/speedscope#312]
Hi. I've setted up speedscope along with a profile service on the same host:port endpoint. Currently I need to specify the url like this:

http://my.fancy.host:29998/#profileURL=http%3A%2F%2Fmy.fancy.host%3A29998%2Fquery_profile%3Fquery_profile_id%3De5a566dd-af4a-4ff9-b597-1a85a50a0136

Can it be reduced to  http://my.fancy.host:29998/#profileURL=query_profile%3Fquery_profile_id%3De5a566dd-af4a-4ff9-b597-1a85a50a0136   ?

**Comment by jlfwong** [comment]
Hi @amosbird!

What happens when you try this? What URL does it try to load? Does it work fi you prefix the `query_profile` with a `/` to `/query_profile` instead?

**Comment by amosbird** [comment]
Hi @jlfwong ! I've tried both and neither worked.

**Comment by jlfwong** [comment]
If you look in the network tab, what URL is it trying to load instead? Are there any errors in the console? What does the network tab show the problem as?

I don't have a setup at the moment that uses `profileURL` in this way, so it's difficult for me to provide guidance without more information

**Comment by amosbird** [comment]
network tab shows both have received the profile from `query_profile` endpoint successfully. However, console prints the following error:

```
Failed to load format TypeError: Failed to construct 'URL': Invalid URL
    at x.<anonymous> (application.tsx:376)
    at Generator.next (<anonymous>)
    at n (application.tsx:540)
```

**Comment by amosbird** [comment]
@jlfwong Hello again :)  Do you require additional information for this?

**Comment by jlfwong** [comment]
Hi! I still haven't reproduced the bug in this task, though I admittedly also haven't really tried.

If you'd like this to have the best shot of being looked at and fixed, it would be helpful if you could provide a detailed step-by-step bug report of the problems you're running into here. In that case, that would be something like commands to start up a simple server, with expected behaviour and actual behaviour. The best case here would be a git repository that I can clone and run a single command to see the issue.

Without reproducing the issue, I can't debug it, and the less effort it takes me to get to the point where I can reproduce it, the more likely I am to want to do it

**Comment by amosbird** [comment]
Ok. Most likely some logic needs to be added here https://github.com/jlfwong/speedscope/blob/master/src/views/application.tsx#L376 

That is, when `profileURL` only contains URL path, filling the host:port information from the current page... I'm not sure if that's the correct way.
