### ISSUE TITLE
Trace event profiles containing multiple 'X' events w/ identical ts & dur fail to import

### ISSUE THREAD

**Issue by nyanpasu64** [jlfwong/speedscope#320]
I'm using speedscope to analyze clang's `-ftime-trace`. However speedscope is unable to analyze some of my .json files (possibly due to updating to Clang 11).

"😿 Something went wrong. Check the JS console for more details."

```
Failed to load format Error: Tried to leave frame "DebugType {"detail":"std::_Locinfo"}" while frame "DebugType {"detail":"const std::_Locinfo"}" was at the top at 3403256
    _leaveFrame https://www.speedscope.app/speedscope.a3aeba39.js:168
    leaveFrame https://www.speedscope.app/speedscope.a3aeba39.js:168
    o https://www.speedscope.app/import.1c646c77.js:111
    p https://www.speedscope.app/import.1c646c77.js:111
    S https://www.speedscope.app/import.1c646c77.js:113
    s https://www.speedscope.app/import.1c646c77.js:113
```

or similar errors. I uploaded two files, one of which breaks speedscope:

[speedscope-json.zip](https://github.com/jlfwong/speedscope/files/5416452/speedscope-json.zip)

- output.cpp.json works.
- sample_docs.cpp.json throws an error, but with a much longer stack trace.

This seems similar but not identical to https://github.com/jlfwong/speedscope/issues/299.

```
C:\Users\nyanpasu>clang --version
clang version 11.0.0
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files\LLVM\bin
```

**Comment by jlfwong** [comment]
Hi @nyanpasu64!

That's a... weird case. It looks like what's happening is that the function call to begin a stack frame doesn't match the function call to end the stack frame in the profile itself. Basically what that line suggests is that somewhere in the profile does this:

```
begin frame DebugType {"detail":"std::_Locinfo"}
end frame DebugType {"detail":"const std::_Locinfo"}
```

speedscope doesn't know anything about what the detail field means, it just assumes it will exactly match between the begin and end frame. Since they don't match, it assumes the profile is malformed.

So AFAICT, this is a bug in clang.

From the `sample_docs.cpp.json` file, I get the following error:

![image](https://user-images.githubusercontent.com/150329/96766172-8b1b3800-138f-11eb-803f-7c4e3ab8209e.png)

Here are the two offending events:

![image](https://user-images.githubusercontent.com/150329/96766141-7b035880-138f-11eb-9428-b12fa62900bc.png)

So you can see that it's semantically trying to say that it's ending the "basic_string_view" frame while the "bool" frame is still open, which doesn't make any sense.

**Comment by nyanpasu64** [comment]
I tried preparing a minimal test case, but it appears to be a heisenbug of sorts, where adding/removing comments or includes can make/break the .json, and the same filesystem tree may sometimes but not always work. Some of this unpredictability may be due to ccache though.

I think I've found the cause in the source .json (not the one I uploaded, but a different compile I autoformatted):

```json
        {
            "pid": 5664,
            "tid": 2752,
            "ph": "X",
            "ts": 1084885,
            "dur": 605,
            "name": "DebugType",
            "args": {
                "detail": "std::_Locinfo"
            }
        },
        {
            "pid": 5664,
            "tid": 2752,
            "ph": "X",
            "ts": 1084885,
            "dur": 605,
            "name": "DebugType",
            "args": {
                "detail": "const std::_Locinfo"
            }
        },
```

From reading the spec, "X" events act as a B/E pair. And apparently clang uses the same ts and dur for "std::_Locinfo" and "const std::_Locinfo". Is this a bug to report to Clang?

**Comment by jlfwong** [comment]
Ahhh, sorry I think I might've been misinterpreting the bug. I assumed the original trace was `B` and `E` events, but that's the result of [this code](https://github.com/jlfwong/speedscope/blob/aee2dfdf89dee9e990c5237ab25569f44fa6a500/src/import/trace-event.ts#L82-L114) automatically converting `X` events into `B` and `E` pairs.

I think this is a bug in speedscope.

The behavior of multiple `X` events w/ the same `ts` and `dur` is ambiguous to me because it has two different, valid interpretations. One is that `std::_LocInfo` should be nested inside of `const std::_Locinfo`, and the other interpretation is the opposite. Probably the correct interpretation is to assume whichever one occurred in the trace first is the outermost event. This is a little tricky because the trace event format specifically says that events can be out of timestamp-order, so I sort, so I'll need to be careful about ensuring that I'm doing a stable sort.

Thanks for digging into this! Here's the minimal repro:

```
[
        {
            "pid": 0,
            "tid": 0,
            "ph": "X",
            "ts": 0,
            "dur": 10,
            "name": "A",
            "args": {
                "x": "1"
            }
        },
        {
            "pid": 0,
            "tid": 0,
            "ph": "X",
            "ts": 0,
            "dur": 10,
            "name": "A",
            "args": {
                "x": "2"
            }
        }
]
```

**Comment by jlfwong** [comment]
@nyanpasu64 Thanks for the really clear report & the minimal repro! The fix is now published to npm and should be live on https://www.speedscope.app/

**Comment by nyanpasu64** [comment]
It works now! Thanks for fixing it!
