### ISSUE TITLE
Instant events?

### ISSUE THREAD

**Issue by elibarzilay** [jlfwong/speedscope#328]
Good morning,

I'm working on some new TS functionality for debugging performance of typechecking.  When I was looking for tools that could be used, I saw this, which looked like it has a simple but convenient UI.  But one thing that I'm looking for is to also see instant events (`"ph":"I"`) -- and it looks like speedscope is ignoring them.  For example, chrome's `about://tracing` shows them as a line that cuts through the graph:

![image](https://user-images.githubusercontent.com/185905/101126275-21ff2500-35c9-11eb-9574-bd2617239474.png)

(but the devtools version ignores them too, though I think they said somewhere that it will be added in some upcoming version).

In any case, can these be rendered too?

(Sidequestion: when I played with this about a month ago, I think that I had no problems loading big dumps, but when I tried it now, it took a very long time to load a ~70mb dump file (didn't measure, but it was more than a minute, enough for chrome to offer killing the page around 3-5 times).  Was there some recent regression?  -- The same dump takes just a few seconds (<5) with devtools/tracing.)

**Comment by jlfwong** [comment]
Hi @elibarzilay!

Re: instant events, it's certainly possible, but it's a reasonable amount of work since it requires changing core data structures, and therefore also the file format to support these. This kind of thing would also be useful for e.g. showing frame boundaries imported from Chrome developer tools. If I'm being honest, I'm unlikely to work on this in the near future.

Re: regression, if you can provide a file, and can test out on older releases from https://github.com/jlfwong/speedscope/releases (you can just download the zip file and double click on `index.html`), then that would be a way of seeing if there was indeed a regression. It's definitely possible -- I've had to change quite a lot about chrome://tracing imports for correctness, and it's possible it got much slower in the process. If you can provide a file, then this is something I'm more likely to have time to look into. If you wouldn't mind opening a separate issue for that if you are able to verify, however, that would be appreciated!

**Comment by elibarzilay** [comment]
@jlfwong, thanks for the clarifications.  I'll try to play around with older versions if I can get to it, and if there is indeed a regression I'll open a new ticket.

Thanks!
