### ISSUE TITLE
Status bar keeps loading, nothing happens

### ISSUE THREAD

**Issue by jmakov** [jlfwong/speedscope#372]
Recorded profile with py-spy v0.3.9, tried online and offline app.

**Comment by jlfwong** [comment]
Hi @jmakov, sorry for the very late response.

Without a specific profile file to debug this with, I won't be able to make progress in seeing what the problem is here. If you can provide a file that causes this crash, then I'll reopen the issue.

Thanks!

**Comment by interdigitaltrainee** [comment]
I am facing similar issue, 

This happens when I try to load large files.

I tried to load,
500MB: OK
1GB: OK
1.5GB: OK but struggles to navigate
>2GB: FAILS

This happens for scope data or with perf generated data at locally installed via npm or via speedscope.app


import.7f8cb9f9.js:42 Uncaught Error: Expected reader.result to be an instance of ArrayBuffer
    at FileReader.<anonymous> (import.7f8cb9f9.js:42:3912)
