### ISSUE TITLE
XCode Instruments 16 breaks Deep Copy format import

### ISSUE THREAD

**Issue by akumansley** [jlfwong/speedscope#481]
Here's a sample Deep Copy from Instruments 16, which seems to have slightly different spacing:

```
Weight	Self Weight	Symbol Names
2.18 s  100.0%	0 s	 node (98674)
1.98 s  90.8%	0 s	  start
1.98 s   0.0%	0 s	   node::Start(int, char**)
1.98 s   0.0%	0 s	    node::LoadSnapshotDataAndRun(node::SnapshotData const**, node::InitializationResult const*)
1.98 s   0.0%	0 s	     node::NodeMainInstance::Run()
```

**Comment by jlfwong** [comment]
Hi! Thanks for the heads up. I'd accept a PR to resolve this while still maintaining functionality for past versions of Instruemnts. The relevant file to change is `importFromInstrumentsDeepCopy`

**Comment by MAUIoxo** [comment]
Hi there,
unfortunately, I also have a broken .trace from use of XCode 16. When do you think it can go productive with this fix?

**Comment by jlfwong** [comment]
@akumansley @robert3005 This is now merged and live on https://www.speedscope.app/

@MAUIoxo Unfortunately, I think your issue is slightly different an unlikely to be resolved. Instruments' file format has evolved significantly since I wrote the support for Instruments import and I never got around to doing the added reverse engineering work to figure out what's going on. See #196. It's possible using "deep copy" as a workaround will still allow you to accomplish what you need to though.

**Comment by xldenis** [comment]
<img width="804" height="188" alt="Image" src="https://github.com/user-attachments/assets/0438570a-824a-4382-a649-d887202ef2f0" />

I'm getting errors when using Deep Copy with Instruments 16, seems like something in the format is mis-aligned I'll see if I can narrow it down further.
