### ISSUE TITLE
Support import from URL specified by #import-url= hash param

### ISSUE THREAD

**Issue by jlfwong** [jlfwong/speedscope#6]

**Comment by alangpierce** [comment]
I'll try taking this on, I think it shouldn't be so bad. I also would like a hash param to give a custom title at the top of the flamechart. One use case is an iframe embedded in a chrome dev tools panel, and another use case is opening a flamechart as an external link. In both cases, the URL is to an S3 file with an encrypted access key, and the profile is slightly sensitive (contains function names for my company's internal codebase), which is why it needs to be a hash fragment and never sent to the server. The S3 file has a standard/autogenerated name that isn't very meaningful, which is why I want the Chrome extension to be able to give a custom title, since it has more context.

Some details/bikeshedding:
* I vaguely prefer camelCase query params and was thinking `profileURL` (it doesn't really feel like an import, at least in my context; you're just using speedscope to view that particular flamechart). But I'm also cool with kebab-case.
* I'm thinking it should be ampersand-delimited with URL-encoded values, just like query params, e.g. `https://jlfwong.github.io/speedscope/#profile-url=http%3A%2F%2Fwww.google.com&title=My%20cool%20profile`. Seem reasonable?
* I think it would be best to best to view it as a special mode that doesn't show the intro screen even for the initial render.

**Comment by jlfwong** [comment]
Fixed by #19
