### ISSUE TITLE
Document, export, and re-import a speedscope json file format

### ISSUE THREAD

**Issue by uber-mahyar2** [jlfwong/speedscope#65]
Since this app can read many trace formats, it would be pretty cool if we could have an export function into some sort of common JSON format.  That way we can use it to convert things like proprietary instruments traces into open chrome traces so we can use it with other tools.

**Comment by jlfwong** [comment]
I would like to define a file format for speedscope to export, so this makes sense to me!

I just want to make sure I understand your request though. When you talk about "convert things like proprietary instruments traces into open chrome traces", it sounds like you might be talking about not only having a common JSON format export, but also being able to export to many different formats.

Or perhaps you were suggesting to export to a single format, and have that format be compatible with the `.cpuprofile` format used by Google Chrome?

**Comment by jlfwong** [comment]
Woah! I didn't know that was documented! That would have been very useful earlier on in building speedscope :)

Chrome has two different profiling formats. One contains just CPU profiling information, and usually has a `.cpuprofile` extension. The other is a superset and conforms to the format described in the document you linked. In the case of that one, the entire sampling profile is crammed into a single "event" entry in the trace with the name `CpuProfile`.

So if I was generating the variety of trace file that Chrome would actually import and display the flamechart for, I would similarly be generating a trace file with a single event.

I still have more questions about the intended use of this.

Is it:
1. That you'd like to use existing other tools that already understand the trace format?
2. That you'd like to write your own tools to filter and manipulate traces before importing them into speedscope?
3. Write your own tools that could convert *into* this format so that speedscope can import them? 

I'm asking because I think I'd rather define my own file format that I can easily evolve without needing to track a changing standard for another tool, and I'm unsure if doing so would still meet your needs.

**Comment by uber-mahyar2** [comment]
It's all 3 reasons for the most part.   But any defined JSON format is really ok, it's not a lot of work to make other tools able to read your speed scope format as long as it's defined in some sort of defined JSON format.

For example:
1. A bunch of our tools do use the chrome format.   
2. Some times I do want to filter out about 10 spammy span types before I import them into a trace visualizer.
3. We have [nanoscope](https://github.com/uber/nanoscope) files and people might be interested in using your visualizer with them.

**Comment by jlfwong** [comment]
Thanks for clarifying! I'll keep you posted on the progress of this. It would be great to have feedback on the usability of the format once I have a proposal

**Comment by jlfwong** [comment]
@uber-mahyar2 I have a draft of a file format spec here: https://github.com/jlfwong/speedscope/pull/83/files#diff-174b392269ff541869d66377c701d775 Any feedback you have about the format would be helpful!

I intend to generate a JSON schema to go along with it in that PR as well

**Comment by jlfwong** [comment]
@uber-mahyar2 These changes have landed and show now be live on https://www.speedscope.app/ 🙂

**Comment by uber-mahyar2** [comment]
Thank you :)

Quick bug report, pressing export on large traces (like a 2 minute high frequency instruments trace) freezes the UI for a while.  Maybe put a progress bar like you have with imports?

**Comment by jlfwong** [comment]
@uber-mahyar2 Filed as #89
