### ISSUE TITLE
Better labels for the time axis

### ISSUE THREAD

**Issue by rudro** [jlfwong/speedscope#90]
First, it would really help if we could simplify how time > 1 minute is shown.  It's hard to parse 1.20min as 1:12 (have to constantly multiply the fraction by 60 to understand seconds). 

Second, only 2 decimals are shown, once you pass 1 minute, instead of 10ms as the finest grain now you only see 0.01 minutes (600ms) as the finest grain. To improve this it would be best if we could get a mm:ss.iii format (minutes:seconds.millisconds) instead. You can look at the timeline in Instruments to see a demo of what this would look like.

Thanks!

**Comment by jlfwong** [comment]
Hi @rudro!

The relevant code for this is fairly isolated: https://github.com/jlfwong/speedscope/blob/master/value-formatters.ts#L15. If you'd like to take a crack at fixing some of these things, I'd be happy to review and merge.

Getting started should be as easy as cloning the repository and running:

```
npm install
npm run serve
```

in the root of the repository.

Otherwise I'll try to get around to this eventually :)
